server:
  port: 8082

# id сервера-приложения eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:
        - id: booksRoute
          uri: http://localhost:8082
          predicates:
            - Path=/books-client/**
          filters:
            - RewritePath=/booksClient/(?<remaining>.*), /$\{remaining}

# url, где будет происходить регистрация микросервисов и другие важные действия
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

